1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [3]:
print(np.__version__)

2.1.3


3. Создайте вектор со значениями от 10 до 49 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
vek=np.arange(10,50)
print(vek)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
vek=np.arange(10,50)
v=np.flip(vek)
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [12]:
A = np.random.random((5,5))
print(A)

[[0.64358985 0.77621004 0.68329018 0.91774474 0.91328176]
 [0.21473351 0.63715337 0.92090262 0.7721383  0.26861897]
 [0.49428744 0.85288126 0.17350766 0.7782993  0.3882513 ]
 [0.8929048  0.81732248 0.71134781 0.1656408  0.91518786]
 [0.08368765 0.15504735 0.43085952 0.99051854 0.85670333]]


array([0.78682331, 0.56270935, 0.53744539, 0.70048075, 0.50336328])

In [9]:
A = np.random.random((5,5))
print(A)
print(np.mean(A,axis=1))
print(np.median(A,axis=1))

[[0.54751222 0.43881164 0.81424095 0.77835755 0.35653475]
 [0.08864877 0.50066297 0.46335552 0.05213313 0.94662757]
 [0.04814463 0.70171644 0.9204503  0.0592591  0.76754409]
 [0.0018775  0.1464516  0.17192454 0.10114379 0.19828795]
 [0.08107802 0.50227913 0.253061   0.27496705 0.33443893]]
[0.58709142 0.41028559 0.49942291 0.12393708 0.28916483]
[0.54751222 0.46335552 0.70171644 0.1464516  0.27496705]


array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [ ]:
a = np.array([x for x in range(27)])

In [10]:
a = np.array([x for x in range(27)]).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [40]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


In [14]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])
b=np.astype(a,int)
print(b)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [36]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [16]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])
b=np.astype(a,bool)
print(b)


[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [38]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])
res=np.hstack((a1,a2))
print(res)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [42]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [20]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])
res=np.vstack((a1,a2))
print(res)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [44]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

(array([0, 3, 4], dtype=int64),)


In [23]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
print(np.where(a==b))

(array([0, 3, 4]),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [54]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [26]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])
res=np.dot(a,b)
print(res)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [59]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [65]:
angles = np.array([3.14, 3.14/2, 6.28])

[ 0.00159265  0.99999968 -0.0031853 ]


In [29]:
angles = np.array([3.14, 3.14/2, 6.28])
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [68]:
v = np.random.random(size=[10])
print(v)

[0.30821184 0.13178341 0.88810901 0.51581108 0.87313982 0.79408365
 0.26204075 0.14962622 0.45199466 0.34446024]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


In [27]:
v = np.random.random(size=[10])
print(v)
res=np.sort(v)
print(res)

[0.4496807  0.48392041 0.64481895 0.79203274 0.8502304  0.9476035
 0.6924913  0.16628904 0.12416003 0.3013075 ]
[0.12416003 0.16628904 0.3013075  0.4496807  0.48392041 0.64481895
 0.6924913  0.79203274 0.8502304  0.9476035 ]


16. Проверить, одинаковы ли два NumPy массива

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

True


In [33]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(a==b)
print(np.allclose(a,b))


[ True  True  True  True  True]
True


17. В одномерном массиве заменить максимальный элемент на ноль

In [73]:
Z = np.random.random(10)

In [74]:
Z

array([0.16782157, 0.13655578, 0.59454878, 0.02957322, 0.81242629,
       0.71645444, 0.48757387, 0.05812814, 0.21499663, 0.24011352])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


In [36]:
Z = np.random.random(10)
print(Z)
a=np.argmax(Z)
Z[a]=0
print(Z)


[0.75761395 0.78422862 0.2595162  0.313406   0.88023922 0.7660925
 0.38227871 0.86778682 0.30952368 0.57213152]
[0.75761395 0.78422862 0.2595162  0.313406   0.         0.7660925
 0.38227871 0.86778682 0.30952368 0.57213152]


18. Замените все нечетные числа одномерного массива на -1.

In [39]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.where(arr % 2 != 0, -1, arr)

In [41]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [42]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [43]:
arr = np.where(arr > 30, 10, arr)
arr = np.where(arr < 5, 10, arr)

In [44]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [45]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [46]:
print(np.sort(a, axis = 0))

[[ 4  5  3]
 [ 7  8  6]
 [11 15 19]]
